### ISSUE TITLE
NoSuchMethodError: com.nirima.jenkins.plugins.docker.DockerTemplate.getDisplayName

### ISSUE THREAD

**Issue by jaryn** [carlossg/jenkins-kubernetes-plugin#5]
Hi

It (Kubernetes plugin 0.2) fails to create the slave after starting the job pinned to the template using the label:

```
Aug 13, 2015 3:53:13 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Excess workload after pending Spot instances: 1
Aug 13, 2015 3:53:13 PM hudson.triggers.SafeTimerTask run
SEVERE: Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@33e98f35 failed
java.lang.NoSuchMethodError: com.nirima.jenkins.plugins.docker.DockerTemplate.getDisplayName()Ljava/lang/String;
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.provision(KubernetesCloud.java:234)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:678)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:284)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:57)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:775)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

the relevant part of jenkins config:
```
  <clouds>
    <org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud plugin="kubernetes@0.2">
      <name>cm-ci-kube</name>
      <templates>
        <com.nirima.jenkins.plugins.docker.DockerTemplate plugin="docker-plugin@0.11.0">
          <configVersion>2</configVersion>
          <labelString>cm-ci-kube-cloud</labelString>
          <launcher class="com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher">
            <sshConnector plugin="ssh-slaves@1.9">
              <port>22</port>
              <jvmOptions></jvmOptions>
              <javaPath></javaPath>
              <maxNumRetries>0</maxNumRetries>
              <retryWaitTime>0</retryWaitTime>
            </sshConnector>
          </launcher>
          <remoteFsMapping></remoteFsMapping>
          <remoteFs>/home/jenkins</remoteFs>
          <instanceCap>1</instanceCap>
          <mode>NORMAL</mode>
          <retentionStrategy class="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">
            <idleMinutes>10</idleMinutes>
            <idleMinutes defined-in="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">10</idleMinutes>
          </retentionStrategy>
          <numExecutors>1</numExecutors>
          <dockerTemplateBase>
            <image>csanchez/jenkins-slave</image>
            <dockerCommand></dockerCommand>
            <lxcConfString></lxcConfString>
            <hostname></hostname>
            <dnsHosts/>
            <volumes/>
            <volumesFrom2/>
            <environment/>
            <bindPorts></bindPorts>
            <bindAllPorts>false</bindAllPorts>
            <privileged>false</privileged>
            <tty>false</tty>
            <extraHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
              <c class="list"/>
              <list reference="../c"/>
            </extraHosts>
          </dockerTemplateBase>
          <removeVolumes>false</removeVolumes>
          <pullStrategy>PULL_LATEST</pullStrategy>
        </com.nirima.jenkins.plugins.docker.DockerTemplate>
      </templates>
      <serverUrl>http://W.X.Y.Z:8080</serverUrl>
      <serverCertificate></serverCertificate>
      <jenkinsUrl></jenkinsUrl>
      <jenkinsTunnel></jenkinsTunnel>
      <username></username>
      <password></password>
      <containerCap>10</containerCap>
    </org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud>
  </clouds>
```

**Comment by jaryn** [comment]
Hmm just after the first start I am getting

```
INFO: Excess workload after pending Spot instances: 1
Aug 14, 2015 8:28:32 AM io.fabric8.utils.cxf.WebClients configureCaCert
SEVERE: Could not create trust manager for null
java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:108)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at io.fabric8.utils.cxf.WebClients.createTrustStore(WebClients.java:68)
	at io.fabric8.utils.cxf.WebClients.configureCaCert(WebClients.java:82)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesFactoryAdapter.createWebClient(KubernetesFactoryAdapter.java:53)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesFactoryAdapter.createKubernetes(KubernetesFactoryAdapter.java:35)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.connect(KubernetesCloud.java:126)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.addProvisionedSlave(KubernetesCloud.java:345)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.provision(KubernetesCloud.java:230)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:678)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:284)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:57)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:775)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Empty input
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:104)
	... 20 more

```

Is it related? I am not trying to use ssl/tls

**Comment by carlossg** [comment]
the repo has moved to https://github.com/jenkinsci/kubernetes-plugin

and I believe this has been fixed already
