### ISSUE TITLE
Waiting for next available executor

### ISSUE THREAD

**Issue by naveensrinivasan** [carlossg/jenkins-kubernetes-plugin#8]
![image](https://cloud.githubusercontent.com/assets/172697/20436972/45803a6c-ad80-11e6-844c-da9df8f6c656.png)

Using this plugin, the first job that starts instantly boots a new pod.
However, all other jobs that start while a job is already running first show the below two messages:
```
Still waiting to schedule task
Waiting for next available executor
```
```

Making default-48f25a9a7690 offline because it’s not responding
Nov 18, 2016 4:14:10 PM WARNING hudson.node_monitors.ResponseTimeMonitor$1 monitor
Making default-17be308127a5 offline because it’s not responding
Nov 18, 2016 4:14:10 PM WARNING hudson.node_monitors.ResponseTimeMonitor$1 monitor
Making default-48f254201f85 offline because it’s not responding
Nov 18, 2016 4:14:11 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (47/100): default-48f254201f85
Nov 18, 2016 4:14:11 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (47/100): default-48f25a9a7690
Nov 18, 2016 4:14:15 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (21/100): default-49179536cb2f
Nov 18, 2016 4:14:17 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (48/100): default-48f254201f85
Nov 18, 2016 4:14:17 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (48/100): default-48f25a9a7690
Nov 18, 2016 4:14:21 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (22/100): default-49179536cb2f
Nov 18, 2016 4:14:23 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (49/100): default-48f254201f85
Nov 18, 2016 4:14:23 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (49/100): default-48f25a9a7690
Nov 18, 2016 4:14:27 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (23/100): default-49179536cb2f
Nov 18, 2016 4:14:29 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (50/100): default-48f254201f85
Nov 18, 2016 4:14:29 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (50/100): default-48f25a9a7690
Nov 18, 2016 4:14:33 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (24/100): default-49179536cb2f
Nov 18, 2016 4:14:35 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (51/100): default-48f254201f85
Nov 18, 2016 4:14:35 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (51/100): default-48f25a9a7690
Nov 18, 2016 4:14:39 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (25/100): default-49179536cb2f
Nov 18, 2016 4:14:41 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (52/100): default-48f254201f85
Nov 18, 2016 4:14:41 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (52/100): default-48f25a9a7690
Nov 18, 2016 4:14:45 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (26/100): default-49179536cb2f
Nov 18, 2016 4:14:47 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (53/100): default-48f254201f85
Nov 18, 2016 4:14:47 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (53/100): default-48f25a9a7690
Nov 18, 2016 4:14:51 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (27/100): default-49179536cb2f
Nov 18, 2016 4:14:53 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (54/100): default-48f254201f85
Nov 18, 2016 4:14:53 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (54/100): default-48f25a9a7690
Nov 18, 2016 4:14:57 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (28/100): default-49179536cb2f
Nov 18, 2016 4:14:59 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (55/100): default-48f254201f85
Nov 18, 2016 4:14:59 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (55/100): default-48f25a9a7690
Nov 18, 2016 4:15:03 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (29/100): default-49179536cb2f
Nov 18, 2016 4:15:05 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (56/100): default-48f254201f85
Nov 18, 2016 4:15:05 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (56/100): default-48f25a9a7690
Nov 18, 2016 4:15:09 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (30/100): default-49179536cb2f
Nov 18, 2016 4:15:11 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (57/100): default-48f254201f85
Nov 18, 2016 4:15:11 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (57/100): default-48f25a9a7690
Nov 18, 2016 4:15:15 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (31/100): default-49179536cb2f
Nov 18, 2016 4:15:17 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (58/100): default-48f254201f85
Nov 18, 2016 4:15:18 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (58/100): default-48f25a9a7690
Nov 18, 2016 4:15:21 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (32/100): default-49179536cb2f
Nov 18, 2016 4:15:24 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (59/100): default-48f254201f85
Nov 18, 2016 4:15:24 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (59/100): default-48f25a9a7690
Nov 18, 2016 4:15:27 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (33/100): default-49179536cb2f
Nov 18, 2016 4:15:30 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (60/100): default-48f254201f85
Nov 18, 2016 4:15:30 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
Waiting for Pod to be scheduled (60/100): default-48f25a9a7690
Nov 18, 2016 4:15:30 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Terminating Kubernetes instance for slave default-4919e98ab541
Nov 18, 2016 4:15:30 PM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
Revature/core/PR-585 #6 completed: SUCCESS
Nov 18, 2016 4:15:30 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Terminated Kubernetes instance for slave default-4919e98ab541
Nov 18, 2016 4:15:30 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Disconnected computer default-4919e98ab541
Nov 18, 2016 4:15:30 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Terminating Kubernetes instance for slave default-48f254201f85
Nov 18, 2016 4:15:30 PM WARNING org.jenkinsci.remoting.nio.NioChannelHub run
Communication problem
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jenkinsci.remoting.nio.FifoBuffer$Pointer.receive(FifoBuffer.java:137)
	at org.jenkinsci.remoting.nio.FifoBuffer.receive(FifoBuffer.java:310)
	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:561)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Nov 18, 2016 4:15:30 PM WARNING jenkins.slaves.JnlpSlaveAgentProtocol$Handler$1 onClosed
NioChannelHub keys=3 gen=6332409: Computer.threadPoolForRemoting [#15] for default-4919e98ab541 terminated
java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@4ccb8664[name=default-4919e98ab541]
	at org.jenkinsci.remoting.nio.NioChannelHub$NioTransport.abort(NioChannelHub.java:208)
	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:629)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jenkinsci.remoting.nio.FifoBuffer$Pointer.receive(FifoBuffer.java:137)
	at org.jenkinsci.remoting.nio.FifoBuffer.receive(FifoBuffer.java:310)
	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:561)
	... 6 more

Nov 18, 2016 4:15:31 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Terminated Kubernetes instance for slave default-48f254201f85
```
How can I make all jobs instantly use new pods, instead of waiting for existing pods to become available?

**Comment by carlossg** [comment]
You need to check in Kubernetes why the pods are not starting, it could be that you don't have enough resources. Jenkins has created the pod and it is waiting for it to start

**Comment by carlossg** [comment]
BTW the correct repo location is https://github.com/jenkinsci/kubernetes-plugin
